/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-05-15 23:54:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/inc/asset.jsp", Long.valueOf(1715590202939L));
    _jspx_dependants.put("/WEB-INF/views/inc/header.jsp", Long.valueOf(1715588185268L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1715588185235L));
    _jspx_dependants.put("jar:file:/C:/class/code/account-book/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/code/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/inc/sidebar.jsp", Long.valueOf(1715588185268L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write("<meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("<!-- Favicon -->\r\n");
      out.write("<link type=\"image/png\" sizes=\"16x16\" rel=\"icon\"\r\n");
      out.write("	href=\"/account/asset/images/icons8-돈-상자-16.png\">\r\n");
      out.write("<!--     <link href=\"img/favicon.ico\" rel=\"icon\"> -->\r\n");
      out.write("\r\n");
      out.write("<!-- Google Web Fonts -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Icon Font Stylesheet -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Libraries Stylesheet -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("blockquote {\r\n");
      out.write("	display: block;\r\n");
      out.write("	background: #fff;\r\n");
      out.write("	padding: 15px 20px 15px 45px;\r\n");
      out.write("	margin: 0 0 20px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	border-left-color: #ADA0DE;\r\n");
      out.write("	border-right-color: #786CA7;\r\n");
      out.write("	/*Font*/\r\n");
      out.write("	font-family: Georgia, serif;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	line-height: 1.2;\r\n");
      out.write("	color: #666;\r\n");
      out.write("	/*Box Shadow - (Optional)*/\r\n");
      out.write("	-moz-box-shadow: 2px 2px 15px #ccc;\r\n");
      out.write("	-webkit-box-shadow: 2px 2px 15px #ccc;\r\n");
      out.write("	box-shadow: 2px 2px 15px #ccc;\r\n");
      out.write("	/*Borders - (Optional)*/\r\n");
      out.write("	border-left-style: solid;\r\n");
      out.write("	border-left-width: 15px;\r\n");
      out.write("	border-right-style: solid;\r\n");
      out.write("	border-right-width: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("blockquote::before {\r\n");
      out.write("	content: &quot; \\201C &quot;; /*Unicode for Left Double Quote*/\r\n");
      out.write("	/*Font*/\r\n");
      out.write("	font-family: Georgia, serif;\r\n");
      out.write("	font-size: 60px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: #999;\r\n");
      out.write("	/*Positioning*/\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	left: 10px;\r\n");
      out.write("	top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("blockquote::after {\r\n");
      out.write("	/*Reset to make sure*/\r\n");
      out.write("	content: &quot;\r\n");
      out.write("	&\r\n");
      out.write("	quot;;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("blockquote a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("/* 	padding: 0 3px; */\r\n");
      out.write("	/*   color: #c76c0c; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("blockquote a:hover {\r\n");
      out.write("	/*  color: #666; */\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("blockquote em {\r\n");
      out.write("	font-style: italic;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*Default Color Palette*/\r\n");
      out.write("blockquote.default {\r\n");
      out.write("	border-left-color: #656d77;\r\n");
      out.write("	border-right-color: #434a53;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page-description h4 a {\r\n");
      out.write("	font-family: 'TTLaundryGothicB';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".index-page-item-area hr {\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	color: #afb0b2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page-description li a {\r\n");
      out.write("	font-family: 'WavvePADO-Regular';\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	/* 	color: #FC8E57; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>BudgetBuddy</title>\r\n");
      out.write("<head>\r\n");
      out.write(" <link type=\"image/png\" sizes=\"16x16\" rel=\"icon\" href=\"/account/asset/images/icons8-돈-상자-16.png\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/reset.css\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write(" <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/combine.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/chart/chart.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/easing/easing.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/js/moment.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/js/moment-timezone.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("<!-- Google Icon -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"path/to/font-awesome/css/font-awesome.min.css\"> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- JavaScript Libraries -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script src=\"script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- JavaScript Libraries -->\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container-xxl position-relative bg-white d-flex p-0\">\r\n");
      out.write("		<!-- Spinner Start -->\r\n");
      out.write("		<div id=\"spinner\"\r\n");
      out.write("			class=\"show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center\">\r\n");
      out.write("			<div class=\"spinner-border text-primary\"\r\n");
      out.write("				style=\"width: 3rem; height: 3rem;\" role=\"status\">\r\n");
      out.write("				<span class=\"sr-only\">Loading...</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Spinner End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Sidebar Start -->\r\n");
      out.write("		<!-- 사이드바  -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>BudgetBuddy</title>\r\n");
      out.write("<head>\r\n");
      out.write(" <link type=\"image/png\" sizes=\"16x16\" rel=\"icon\" href=\"/account/asset/images/icons8-돈-상자-16.png\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/reset.css\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write(" <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/combine.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/chart/chart.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/easing/easing.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/js/moment.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/js/moment-timezone.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("<!-- Google Icon -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"path/to/font-awesome/css/font-awesome.min.css\"> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- JavaScript Libraries -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script src=\"script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- JavaScript Libraries -->\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<div class=\"sidebar\">\r\n");
      out.write("\r\n");
      out.write("	<div class=\"buddy-budget-logo-style\"><a href=\"/account/index.do\"><span data-attr=\"Budget\">Budget</span><span data-attr=\"Buddy\">Buddy</span></a></div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		<!-- 사이드바 끝  -->\r\n");
      out.write("		<!-- Sidebar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Content Start -->\r\n");
      out.write("		<div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Navbar Start -->\r\n");
      out.write("			<!-- 상당 메뉴 -->\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>BudgetBuddy</title>\r\n");
      out.write("<head>\r\n");
      out.write(" <link type=\"image/png\" sizes=\"16x16\" rel=\"icon\" href=\"/account/asset/images/icons8-돈-상자-16.png\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/reset.css\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write(" <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/combine.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/chart/chart.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/easing/easing.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/js/moment.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/js/moment-timezone.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("<!-- Google Icon -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"path/to/font-awesome/css/font-awesome.min.css\"> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- JavaScript Libraries -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script src=\"script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- JavaScript Libraries -->\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("@import url('https://fonts.googleapis.com/css?family=Rubik:700&display=swap');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* .header-content {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  border: 0;\r\n");
      out.write("  vertical-align: middle;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-size: inherit;\r\n");
      out.write("  font-family: inherit;\r\n");
      out.write("  background-color: rgb(0 0 0 / 0%);\r\n");
      out.write("  \r\n");
      out.write("  &.header-content-item {\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    color: #382b22;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    padding: 1.25em 2em;\r\n");
      out.write("    background: #fff0f0;\r\n");
      out.write("    border: 2px solid #b18597;\r\n");
      out.write("    border-radius: 0.75em;\r\n");
      out.write("    transform-style: preserve-3d;\r\n");
      out.write("    transition: transform 150ms cubic-bezier(0, 0, 0.58, 1), background 150ms cubic-bezier(0, 0, 0.58, 1);\r\n");
      out.write("    &::before {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      content: '';\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      top: 0;\r\n");
      out.write("      left: 0;\r\n");
      out.write("      right: 0;\r\n");
      out.write("      bottom: 0;\r\n");
      out.write("      background: #f9c4d2;\r\n");
      out.write("      border-radius: inherit;\r\n");
      out.write("      box-shadow: 0 0 0 2px #b18597, 0 0.625em 0 0 #A6CCBA;\r\n");
      out.write("      transform: translate3d(0, 0.75em, -1em);\r\n");
      out.write("      transition: transform 150ms cubic-bezier(0, 0, 0.58, 1), box-shadow 150ms cubic-bezier(0, 0, 0.58, 1);\r\n");
      out.write("    }\r\n");
      out.write("    &:hover {\r\n");
      out.write("      background: #ffe9e9;\r\n");
      out.write("      transform: translate(0, 0.25em);\r\n");
      out.write("      &::before {\r\n");
      out.write("        box-shadow: 0 0 0 2px #b18597, 0 0.5em 0 0 #A6CCBA;\r\n");
      out.write("        transform: translate3d(0, 0.5em, -1em);\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("    &:active {\r\n");
      out.write("      background: #ffe9e9;\r\n");
      out.write("      transform: translate(0em, 0.75em);\r\n");
      out.write("      &::before {\r\n");
      out.write("        box-shadow: 0 0 0 2px #b18597, 0 0 #A6CCBA;\r\n");
      out.write("        transform: translate3d(0, 0, -1em);\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  .header-content {\r\n");
      out.write("  	color: #333;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin-left: 100px;\r\n");
      out.write("	margin: 0 20px;\r\n");
      out.write("    border:none;\r\n");
      out.write("        \r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("	  &::before, &::after {\r\n");
      out.write("	    box-sizing: border-box;\r\n");
      out.write("	  }\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .header-content:hover,\r\n");
      out.write("  .header-content.active {\r\n");
      out.write("   	transform: translate(0, 0.25em);\r\n");
      out.write("  	color: #EFFDF6;\r\n");
      out.write("  	font-weight: bold;\r\n");
      out.write("  	font-weight: 600;\r\n");
      out.write("  	text-shadow: 1px -1px 1px #88bfad;\r\n");
      out.write("  }\r\n");
      out.write(" \r\n");
      out.write(" .header-content:hover::before {\r\n");
      out.write(" }\r\n");
      out.write(" .header-content.active::before {\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<header id=\"navheader\">\r\n");
      out.write("	<nav>\r\n");
      out.write("            <div id=\"view-header-btn\" class=\"\">\r\n");
      out.write("           	 	<a href=\"/account/account/calendar.do\" class=\"header-content \">대시보드</a>\r\n");
      out.write("           	 	<a href=\"/account/card/recommendation.do\" class=\"header-content \">카드추천</a>\r\n");
      out.write("           	 	<a href=\"/account/board/view.do\" class=\"header-content \">게시판</a>\r\n");
      out.write("           	 	<a href=\"/account/user/member/info.do\" class=\"header-content \">마이페이지</a>\r\n");
      out.write("           	 	\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("	</nav>\r\n");
      out.write("</header>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("	    const currentPath = window.location.pathname;\r\n");
      out.write("	\r\n");
      out.write("	 	// dropdown-item 요소의 href와 동일한 경우에 active 클래스 추가\r\n");
      out.write("	    const headerContents = document.querySelectorAll('.header-content');\r\n");
      out.write("	\r\n");
      out.write("	    headerContents.forEach(function(item) {\r\n");
      out.write("	        const href = item.getAttribute('href');\r\n");
      out.write("	\r\n");
      out.write("	        if (currentPath === href) {\r\n");
      out.write("// 	            item.classList.add('header-content-item');\r\n");
      out.write("	            item.classList.add('active');\r\n");
      out.write("	        }\r\n");
      out.write("	    });\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		// 현재 URL\r\n");
      out.write("		var currentUrl = window.location.pathname;\r\n");
      out.write("		\r\n");
      out.write("		console.log(currentUrl);\r\n");
      out.write("		\r\n");
      out.write("		// 로그인 페이지나 관련 페이지일 때\r\n");
      out.write("		if (currentUrl.endsWith(\"login.do\") || currentUrl.endsWith(\"/register.do\") || currentUrl.endsWith(\"find-id.do\") || currentUrl.endsWith(\"find-pw.do\") || currentUrl.endsWith(\"reset-pw.do\")) {\r\n");
      out.write("		    // \"header-content\" 클래스를 가진 모든 요소를 숨김\r\n");
      out.write("		    document.querySelectorAll(\".header-content\").forEach(function(item) {\r\n");
      out.write("		        item.style.display = \"none\";\r\n");
      out.write("		    });\r\n");
      out.write("		\r\n");
      out.write("		    // \"header-buddy-budget-logo\" 요소를 추가\r\n");
      out.write("		    var buddyBudgetLogo = document.createElement(\"div\");\r\n");
      out.write("		    buddyBudgetLogo.id = \"header-buddy-budget-logo\";\r\n");
      out.write("		    buddyBudgetLogo.classList.add(\"buddy-budget-logo-style\");\r\n");
      out.write("		    buddyBudgetLogo.innerHTML = '<a href=\"/account/index.do\"><span data-attr=\"Budget\">Budget</span><span data-attr=\"Buddy\">Buddy</span></a>';\r\n");
      out.write("		    document.querySelector(\"header#navheader\").appendChild(buddyBudgetLogo);\r\n");
      out.write("		} else {\r\n");
      out.write("		    // 로그인 페이지나 관련 페이지가 아닐 때는 \"buddy-budget-logo\" 요소를 제거\r\n");
      out.write("		    var buddyBudgetLogo = document.getElementById(\"header-buddy-budget-logo\");\r\n");
      out.write("		    if (buddyBudgetLogo) {\r\n");
      out.write("		        buddyBudgetLogo.remove();\r\n");
      out.write("		    }\r\n");
      out.write("		}	\r\n");
      out.write("		\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<!-- 상당 메뉴 끝-->\r\n");
      out.write("			<!-- Navbar End -->\r\n");
      out.write("			<!-- Content End -->\r\n");
      out.write("			<!-- fakecontent 안에서 작성 -->\r\n");
      out.write("			<div class=\"content-total-style\">\r\n");
      out.write("				<div class=\"index-page\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"index-page-item-area main-box-container-style\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<section>\r\n");
      out.write("								<h2>\r\n");
      out.write("									<span> \"소비 패턴 분석을 통한 </span> <span> 지출 관리 친구\" </span>\r\n");
      out.write("								</h2>\r\n");
      out.write("								<!--             <span>\"Budget</span><span>Buddy\"</span> -->\r\n");
      out.write("							</section>\r\n");
      out.write("						</div>\r\n");
      out.write("						<hr>\r\n");
      out.write("						<div class=\"index-page-box-area\">\r\n");
      out.write("							<blockquote class=\"page-description\">\r\n");
      out.write("								<h4>\r\n");
      out.write("									<a href=\"/account/account/calendar.do\"><i\r\n");
      out.write("										class=\"fas fa-piggy-bank\"></i> 대시보드</a>\r\n");
      out.write("								</h4>\r\n");
      out.write("								<!--             <strong>대시보드는 사용자가 가계부를 효과적으로 관리하고 금융 상황을 시각적으로 파악할 수 있습니다.</strong><br><br> -->\r\n");
      out.write("								<strong>가계부를 작성하여 금융 상황을 시각적으로 파악해보세요!</strong><br>\r\n");
      out.write("								<br>\r\n");
      out.write("								<ol style=\"padding-left: 0\">\r\n");
      out.write("									<li><a href=\"/account/account/calendar.do\"><i class=\"fa-solid fa-calendar-days\"></i> 달력</a><br>&nbsp;\r\n");
      out.write("									카테고리별로 수입과 지출을 기록하고 관리할 수 있습니다.\r\n");
      out.write("									일일, 주간, 월간 중 기간을 선택하여 특정 기간 동안의 기록을 조회할 수 있으며, \r\n");
      out.write("									나만의 구매 위시 목록을 기록하여 지출 내용을 관리할 수 있습니다.</li>\r\n");
      out.write("									<br><hr><br>\r\n");
      out.write("									<li><a href=\"/account/account/list.do\"><i class=\"fa-solid fa-bars\"></i> 목록</a><br>&nbsp; \r\n");
      out.write("									가계부 내용에서 조회하고 싶은 특정 카테고리를 선택하거나 단어를 검색하여 가계부 내역을 필터링하여 조회할 수 있습니다.</li>\r\n");
      out.write("									<br><hr><br>\r\n");
      out.write("									<li><a href=\"/account/account/analysis.do\"><i class=\"fa-solid fa-chart-pie\"></i> 분석</a><br>&nbsp; \r\n");
      out.write("									일일, 주간 월간 기록을 시각적으로 확인할 수 있도록 사용자의 기간별 카테고리 지출을 그래프로 제공합니다.\r\n");
      out.write("									지난 한 달과 이번 달의 지출 카테고리를 비교하여 방향성을 제공하며, 해당 카테고리에 대한 뉴스 정보를 제공합니다. \r\n");
      out.write("									저축 목표를 설정하면 이에 따른 현상황을 파악하고, 지출 금액을 조정할 수 있도록 도와줍니다.</li>\r\n");
      out.write("									<br><hr><br>\r\n");
      out.write("									<li><a href=\"/account/account/card-use.do\"><i class=\"fa-solid fa-credit-card\"></i> 카드 사용 내역</a><br>&nbsp; \r\n");
      out.write("									가계부 기입 내용을 바탕으로 기간별 각 카드의 소비 내역을 파악할 수 있습니다. \r\n");
      out.write("									이를 통해 카드별 사용 금액과 주 소비 카테고리를 파악할 수 있습니다.</li>\r\n");
      out.write("\r\n");
      out.write("									<!-- 				\r\n");
      out.write("				<li><strong>1. 달력</strong>\r\n");
      out.write("				<br>&nbsp;사용자는 대시보드에서 가계부를 기입할 수 있습니다. 이를\r\n");
      out.write("				통해 사용자는 수입과 지출을 기록하고 관리할 수 있습니다. 가계부에는 날짜, 카테고리(식비, 교통, 의류 등),\r\n");
      out.write("				금액, 메모 등의 정보를 입력할 수 있습니다. 새로운 거래를 추가하고 기존 거래를 수정 또는 삭제할 수 있습니다.</li>\r\n");
      out.write("				<br><li><strong>2. 목록</strong><br>&nbsp;\r\n");
      out.write("				사용자는 대시보드에서 가계부의 내용을 조회할 수 있습니다. 이를 통해 사용자는 이전에 기록한 거래 내역을 확인하고 관리할 수 있습니다.\r\n");
      out.write("가계부 조회 기능을 통해 사용자는 특정 기간 동안의 거래 내역을 검색하고 필터링할 수 있습니다.\r\n");
      out.write("소비 부문별로 조회할 수 있어서 식비, 교통비, 생활비 등 각각의 소비 부문에 따른 지출 내역을 확인할 수 있습니다.</li>\r\n");
      out.write("				<br><li><strong>3. 분석</strong><br>&nbsp;\r\n");
      out.write("				대시보드는 사용자의 가계부 데이터를 분석하여 다양한 통계와 그래프를 제공합니다.\r\n");
      out.write("사용자는 소비 부문별로 지출된 금액을 시각적으로 파악할 수 있습니다. 예를 들어, 월별 식비 지출 추이를 확인할 수 있습니다.\r\n");
      out.write("사용자는 수입과 지출의 총액, 각 소비 부문의 비중, 월별 지출 패턴 등을 쉽게 파악할 수 있습니다.</li>\r\n");
      out.write("				<br><li><strong>4. 카드 사용 내역</strong><br>&nbsp;\r\n");
      out.write("				사용자의 카드 사용 내역을 조회하고 카드별 소비 금액을 보여줍니다.\r\n");
      out.write("사용자는 각 카드의 사용 내역을 확인하고 해당 카드로 발생한 소비 금액을 파악할 수 있습니다.\r\n");
      out.write("카드 사용금액 조회를 통해 사용자는 카드별로 어떤 부문에서 얼마나 지출되었는지를 알 수 있습니다.</li>\r\n");
      out.write("			 -->\r\n");
      out.write("\r\n");
      out.write("								</ol>\r\n");
      out.write("							</blockquote>\r\n");
      out.write("							<blockquote class=\"page-description\">\r\n");
      out.write("								<h4>\r\n");
      out.write("									<a href=\"/account/card/recommendation.do\"><i\r\n");
      out.write("										class=\"fa-solid fa-ranking-star\"></i> 카드 추천</a>\r\n");
      out.write("								</h4>\r\n");
      out.write("								<strong>자신의 소비 습관에 적합한 혜택을 제공하는 카드를 추천받아 보세요!</strong><br><br>\r\n");
      out.write("<!-- 								\r\n");
      out.write("								<strong>우리의 가계부 웹사이트는 사용자들이 자신의 소비 습관을 파악하고 최적의 신용카드를\r\n");
      out.write("									선택할 수 있도록 도와줍니다.</strong> <br>\r\n");
      out.write("								<br>\r\n");
      out.write("								<p>&nbsp;이를 위해 소비자 맞춤 카드 추천 기능을 제공합니다. 이 기능은 사용자가 자주 이용하는 소비\r\n");
      out.write("									부문을 기반으로, 해당 부문에서 가장 적합한 혜택을 제공하는 카드를 추천해줍니다.</p>\r\n");
      out.write("\r\n");
      out.write("								<strong>소비자 맞춤 카드 추천의 원리</strong><br> -->\r\n");
      out.write("\r\n");
      out.write("								<li><a href=\"/account/card/recommendation.do\"><i class=\"fa-solid fa-ranking-star\"></i> 카테고리별 추천</a><br>&nbsp;\r\n");
      out.write("									카테고리별로 각 카드가 제공하는 혜택을 기반으로 순위를 매겨 추천합니다.</li> <br>\r\n");
      out.write("								<hr>\r\n");
      out.write("								<br>\r\n");
      out.write("								<li><a href=\"/account/card/personalized-recommendation.do\"><i class=\"fa-solid fa-medal\"></i> 맞춤 추천</a><br>&nbsp; \r\n");
      out.write("									가계부에서 작성한 내용을 기반으로 내가 많이 소비하는 카테고리를 파악하고,\r\n");
      out.write("									나의 소비 패턴과 카드의 혜택을 비교하여 해당 분야에서 혜택이 뛰어난 카드를 추천합니다.</li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								<!-- 								<ol style=\"padding-left: 0\">\r\n");
      out.write("									<li><strong>1. 소비 부문 분석 </strong> <br>&nbsp;사용자의 가계부\r\n");
      out.write("										데이터를 분석하여 어떤 부문에서 가장 많은 소비가 이루어졌는지 확인합니다. 예를 들어, 식료품, 교통, 의류\r\n");
      out.write("										등의 다양한 부문을 고려합니다.</li>\r\n");
      out.write("									<br>\r\n");
      out.write("									<li><strong>2. 카드 혜택 분석 </strong> <br>&nbsp; 다양한 카드의\r\n");
      out.write("										혜택을 수집하고 분석합니다. 이는 카드 회사의 웹사이트, 프로모션 정보, 리워드 프로그램 등을 통해\r\n");
      out.write("										이루어집니다. 각 카드의 혜택은 해당 부문에서 제공되는 할인율, 적립률, 현금 환급 등을 포함합니다.</li>\r\n");
      out.write("									</br>\r\n");
      out.write("									<li><strong>3. 맞춤 카드 추천 </strong> <br>&nbsp;사용자의 소비\r\n");
      out.write("										부문과 카드의 혜택을 고려하여 가장 적합한 카드를 추천합니다. 이를 위해 알고리즘은 사용자의 소비 패턴과 카드의\r\n");
      out.write("										혜택을 비교하여 최적의 조합을 찾습니다. 예를 들어, 식료품을 가장 많이 소비하는 사용자에게는 해당 부문에서\r\n");
      out.write("										할인 혜택이 뛰어난 카드를 추천할 수 있습니다.</li>\r\n");
      out.write("									<br> -->\r\n");
      out.write("								</ol>\r\n");
      out.write("							</blockquote>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!--     	<div class=\"index-page-item-area\">\r\n");
      out.write("        	<img src=\"/account/asset/images/BudgetBuddy.jpg\" alt=\"이미지\">\r\n");
      out.write("        </div> -->\r\n");
      out.write("					<div class=\"index-page-item-area\">\r\n");
      out.write("						<img src=\"/account/asset/images/green-account-book-img.jpeg\" alt=\"이미지\">\r\n");
      out.write("						\r\n");
      out.write("						<blockquote class=\"page-description\">\r\n");
      out.write("								<h4>\r\n");
      out.write("									<a href=\"/account/board/view.do\"><i\r\n");
      out.write("										class=\"fas fa-clipboard\"></i> 게시판</a>\r\n");
      out.write("								</h4>\r\n");
      out.write("								<strong>다양한 게시판을 통해 회원들과 소통하고 정보를 공유해보세요!</strong><br>\r\n");
      out.write("								<br>\r\n");
      out.write("								<ol style=\"padding-left: 0\">\r\n");
      out.write("									<li><a href=\"/account/board/view.do\"><i class=\"fas fa-home\"></i> 게시판 홈</a><br>&nbsp;\r\n");
      out.write("										게시판 카테고리별로 최신 글 목록을 제공합니다.</li> \r\n");
      out.write("<!-- 										\r\n");
      out.write("									<br>\r\n");
      out.write("									<hr>\r\n");
      out.write("									<br>\r\n");
      out.write("									<li><a href=\"/account/board/noticeBoard.do\"><i class=\"fas fa-clipboard\"></i> 공지 게시판</a> <br>&nbsp;\r\n");
      out.write("										중요한 정보나 업데이트 사항을 알리는 공간입니다. 관리자가 회원들이 반드시 알아야 할 사항이나 서비스 변경 사항 정보를 업데이트합니다.</li> <br>\r\n");
      out.write("									<hr>\r\n");
      out.write("									<br>\r\n");
      out.write("								<li><a href=\"/account/board/freeBoard.do\"><i class=\"fas fa-clipboard\"></i> 자유 게시판</a> <br>&nbsp; \r\n");
      out.write("										자유롭게 의견을 나누고 정보를 공유하는 공간입니다. 특정 주제나 제한된 내용없이 다양한 주제에 대해 이야기할 수 있습니다.</li><br>\r\n");
      out.write("									<hr>\r\n");
      out.write("									<br>\r\n");
      out.write("								<li><a href=\"/account/board/attendanceBoard.do\"><i class=\"fas fa-clipboard\"></i> 출석 게시판</a><br>&nbsp; \r\n");
      out.write("										출석 상황을 공유하는 공간입니다. 나의 활동 상태를 공유하며 소통할 수 있습니다.</li><br>\r\n");
      out.write("									<hr>\r\n");
      out.write("									<br>\r\n");
      out.write("								<li><a href=\"/account/board/reportBoard.do\"><i class=\"fas fa-clipboard\"></i> 건의 게시판</a><b``r>&nbsp; \r\n");
      out.write("										서비스에 대한 건의나 개선 사항을 제안하는 공간압니다. 자신의 의견을 나누고 서비스 향상을 위해 제안할 수 있습니다.</li> -->\r\n");
      out.write("\r\n");
      out.write("<!-- 									<li><strong>1. 공지사항 </strong> <br>&nbsp;&nbsp;관리자가\r\n");
      out.write("										회원들에게 중요한 정보나 업데이트 사항을 알리는 공간입니다. 회원들이 반드시 알아야 할 사항이나 서비스의\r\n");
      out.write("										변경사항 등을 여기에 올립니다.</li>\r\n");
      out.write("									<br>\r\n");
      out.write("									<li><strong>2. 건의사항 </strong> <br>&nbsp;&nbsp;회원들이\r\n");
      out.write("										서비스에 대한 건의나 개선 사항을 제안하는 공간입니다. 이 게시판을 통해 회원들은 자신들의 의견을 나누고 서비스\r\n");
      out.write("										향상을 위한 제안을 할 수 있습니다.</li>\r\n");
      out.write("									<br>\r\n");
      out.write("									<li><strong>3. 자유게시판 </strong> <br>&nbsp;&nbsp;회원들이\r\n");
      out.write("										자유롭게 의견을 나누고 정보를 공유하는 공간입니다. 특정 주제나 제한된 내용 없이 다양한 주제에 대해 이야기할\r\n");
      out.write("										수 있습니다.</li>\r\n");
      out.write("									<br>\r\n");
      out.write("									<li><strong>4. 출석게시판 </strong> <br>회원들이 매일 출석체크를 하고\r\n");
      out.write("										&nbsp;&nbsp;출석 현황을 확인하는 공간입니다. 이를 통해 회원들끼리 활동 상태를 공유하고 꾸준한 참여를\r\n");
      out.write("										유도합니다.</li> -->\r\n");
      out.write("								</ol>\r\n");
      out.write("\r\n");
      out.write("							</blockquote>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<script src=\"script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("					<!-- fakecontent 끝 -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- JavaScript Libraries -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Template Javascript -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/js/main.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/inc/header.jsp(109,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	           	 	<a href=\"/account/user/login.do\" class=\"header-content \">로그인</a>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/inc/header.jsp(112,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	           	 	<a href=\"/account/user/logout.do\" class=\"header-content \">로그아웃</a>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
