/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-05-15 23:54:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/inc/asset.jsp", Long.valueOf(1715590202939L));
    _jspx_dependants.put("/WEB-INF/views/inc/header.jsp", Long.valueOf(1715588185268L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1715588185235L));
    _jspx_dependants.put("jar:file:/C:/class/code/account-book/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/code/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>BudgetBuddy | 로그인</title>\r\n");
      out.write("     <link type=\"image/png\" sizes=\"16x16\" rel=\"icon\" href=\"/account/asset/images/icons8-돈-상자-16.png\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/account/asset/css/materialdesignicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/account/asset/css/vendor.bundle.base.css\">\r\n");
      out.write("<!-- plugins:css -->\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"/account/asset/css/style.css\"> -->\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Plugin css for this page -->\r\n");
      out.write("<!-- End plugin css for this page -->\r\n");
      out.write("<!-- inject:css -->\r\n");
      out.write("<!-- endinject -->\r\n");
      out.write("<!-- Layout styles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/account/asset/css/corona\\_style.css\">\r\n");
      out.write("<!-- End layout styles -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/account/asset/images/favicon.png\" />\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".find-info-btn span {\r\n");
      out.write("	color: #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>BudgetBuddy</title>\r\n");
      out.write("<head>\r\n");
      out.write(" <link type=\"image/png\" sizes=\"16x16\" rel=\"icon\" href=\"/account/asset/images/icons8-돈-상자-16.png\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/reset.css\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write(" <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/combine.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/chart/chart.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/easing/easing.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/js/moment.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/js/moment-timezone.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("<!-- Google Icon -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"path/to/font-awesome/css/font-awesome.min.css\"> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- JavaScript Libraries -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script src=\"script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- JavaScript Libraries -->\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>BudgetBuddy</title>\r\n");
      out.write("<head>\r\n");
      out.write(" <link type=\"image/png\" sizes=\"16x16\" rel=\"icon\" href=\"/account/asset/images/icons8-돈-상자-16.png\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/reset.css\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write(" <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/combine.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/chart/chart.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/easing/easing.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/js/moment.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/js/moment-timezone.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("<!-- Google Icon -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"path/to/font-awesome/css/font-awesome.min.css\"> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- JavaScript Libraries -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script src=\"script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- JavaScript Libraries -->\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/asset/css/temp/js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("@import url('https://fonts.googleapis.com/css?family=Rubik:700&display=swap');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* .header-content {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  border: 0;\r\n");
      out.write("  vertical-align: middle;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-size: inherit;\r\n");
      out.write("  font-family: inherit;\r\n");
      out.write("  background-color: rgb(0 0 0 / 0%);\r\n");
      out.write("  \r\n");
      out.write("  &.header-content-item {\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    color: #382b22;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    padding: 1.25em 2em;\r\n");
      out.write("    background: #fff0f0;\r\n");
      out.write("    border: 2px solid #b18597;\r\n");
      out.write("    border-radius: 0.75em;\r\n");
      out.write("    transform-style: preserve-3d;\r\n");
      out.write("    transition: transform 150ms cubic-bezier(0, 0, 0.58, 1), background 150ms cubic-bezier(0, 0, 0.58, 1);\r\n");
      out.write("    &::before {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      content: '';\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      top: 0;\r\n");
      out.write("      left: 0;\r\n");
      out.write("      right: 0;\r\n");
      out.write("      bottom: 0;\r\n");
      out.write("      background: #f9c4d2;\r\n");
      out.write("      border-radius: inherit;\r\n");
      out.write("      box-shadow: 0 0 0 2px #b18597, 0 0.625em 0 0 #A6CCBA;\r\n");
      out.write("      transform: translate3d(0, 0.75em, -1em);\r\n");
      out.write("      transition: transform 150ms cubic-bezier(0, 0, 0.58, 1), box-shadow 150ms cubic-bezier(0, 0, 0.58, 1);\r\n");
      out.write("    }\r\n");
      out.write("    &:hover {\r\n");
      out.write("      background: #ffe9e9;\r\n");
      out.write("      transform: translate(0, 0.25em);\r\n");
      out.write("      &::before {\r\n");
      out.write("        box-shadow: 0 0 0 2px #b18597, 0 0.5em 0 0 #A6CCBA;\r\n");
      out.write("        transform: translate3d(0, 0.5em, -1em);\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("    &:active {\r\n");
      out.write("      background: #ffe9e9;\r\n");
      out.write("      transform: translate(0em, 0.75em);\r\n");
      out.write("      &::before {\r\n");
      out.write("        box-shadow: 0 0 0 2px #b18597, 0 0 #A6CCBA;\r\n");
      out.write("        transform: translate3d(0, 0, -1em);\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  .header-content {\r\n");
      out.write("  	color: #333;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin-left: 100px;\r\n");
      out.write("	margin: 0 20px;\r\n");
      out.write("    border:none;\r\n");
      out.write("        \r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("	  &::before, &::after {\r\n");
      out.write("	    box-sizing: border-box;\r\n");
      out.write("	  }\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .header-content:hover,\r\n");
      out.write("  .header-content.active {\r\n");
      out.write("   	transform: translate(0, 0.25em);\r\n");
      out.write("  	color: #EFFDF6;\r\n");
      out.write("  	font-weight: bold;\r\n");
      out.write("  	font-weight: 600;\r\n");
      out.write("  	text-shadow: 1px -1px 1px #88bfad;\r\n");
      out.write("  }\r\n");
      out.write(" \r\n");
      out.write(" .header-content:hover::before {\r\n");
      out.write(" }\r\n");
      out.write(" .header-content.active::before {\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<header id=\"navheader\">\r\n");
      out.write("	<nav>\r\n");
      out.write("            <div id=\"view-header-btn\" class=\"\">\r\n");
      out.write("           	 	<a href=\"/account/account/calendar.do\" class=\"header-content \">대시보드</a>\r\n");
      out.write("           	 	<a href=\"/account/card/recommendation.do\" class=\"header-content \">카드추천</a>\r\n");
      out.write("           	 	<a href=\"/account/board/view.do\" class=\"header-content \">게시판</a>\r\n");
      out.write("           	 	<a href=\"/account/user/member/info.do\" class=\"header-content \">마이페이지</a>\r\n");
      out.write("           	 	\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("	</nav>\r\n");
      out.write("</header>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("	    const currentPath = window.location.pathname;\r\n");
      out.write("	\r\n");
      out.write("	 	// dropdown-item 요소의 href와 동일한 경우에 active 클래스 추가\r\n");
      out.write("	    const headerContents = document.querySelectorAll('.header-content');\r\n");
      out.write("	\r\n");
      out.write("	    headerContents.forEach(function(item) {\r\n");
      out.write("	        const href = item.getAttribute('href');\r\n");
      out.write("	\r\n");
      out.write("	        if (currentPath === href) {\r\n");
      out.write("// 	            item.classList.add('header-content-item');\r\n");
      out.write("	            item.classList.add('active');\r\n");
      out.write("	        }\r\n");
      out.write("	    });\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		// 현재 URL\r\n");
      out.write("		var currentUrl = window.location.pathname;\r\n");
      out.write("		\r\n");
      out.write("		console.log(currentUrl);\r\n");
      out.write("		\r\n");
      out.write("		// 로그인 페이지나 관련 페이지일 때\r\n");
      out.write("		if (currentUrl.endsWith(\"login.do\") || currentUrl.endsWith(\"/register.do\") || currentUrl.endsWith(\"find-id.do\") || currentUrl.endsWith(\"find-pw.do\") || currentUrl.endsWith(\"reset-pw.do\")) {\r\n");
      out.write("		    // \"header-content\" 클래스를 가진 모든 요소를 숨김\r\n");
      out.write("		    document.querySelectorAll(\".header-content\").forEach(function(item) {\r\n");
      out.write("		        item.style.display = \"none\";\r\n");
      out.write("		    });\r\n");
      out.write("		\r\n");
      out.write("		    // \"header-buddy-budget-logo\" 요소를 추가\r\n");
      out.write("		    var buddyBudgetLogo = document.createElement(\"div\");\r\n");
      out.write("		    buddyBudgetLogo.id = \"header-buddy-budget-logo\";\r\n");
      out.write("		    buddyBudgetLogo.classList.add(\"buddy-budget-logo-style\");\r\n");
      out.write("		    buddyBudgetLogo.innerHTML = '<a href=\"/account/index.do\"><span data-attr=\"Budget\">Budget</span><span data-attr=\"Buddy\">Buddy</span></a>';\r\n");
      out.write("		    document.querySelector(\"header#navheader\").appendChild(buddyBudgetLogo);\r\n");
      out.write("		} else {\r\n");
      out.write("		    // 로그인 페이지나 관련 페이지가 아닐 때는 \"buddy-budget-logo\" 요소를 제거\r\n");
      out.write("		    var buddyBudgetLogo = document.getElementById(\"header-buddy-budget-logo\");\r\n");
      out.write("		    if (buddyBudgetLogo) {\r\n");
      out.write("		        buddyBudgetLogo.remove();\r\n");
      out.write("		    }\r\n");
      out.write("		}	\r\n");
      out.write("		\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container-scroller\">\r\n");
      out.write("		<div class=\"content-total-style\">\r\n");
      out.write("			<div class=\"user-info-input-page-container login-page-container user-info-box-container-style\">\r\n");
      out.write("				<div class=\"user-info-container-style\">\r\n");
      out.write("					<div class=\"\">\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<h3 class=\"card-title text-left mb-3\">로그인</h3>\r\n");
      out.write("							<form method=\"POST\" action=\"/account/user/login.do\">\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<label>아이디</label> <input type=\"text\" name=\"id\"\r\n");
      out.write("										class=\"form-control input-style-form\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"form-group\">\r\n");
      out.write("									<label>비밀번호</label> <input type=\"password\" name=\"pw\"\r\n");
      out.write("										class=\"form-control input-style-form\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div\r\n");
      out.write("									class=\"form-group d-flex align-items-center justify-content-between\">\r\n");
      out.write("									<div class=\"form-check\">\r\n");
      out.write("										<label class=\"form-check-label\"> <input\r\n");
      out.write("											type=\"checkbox\" class=\"form-check-input\" name=\"autoLogin\">자동 로그인\r\n");
      out.write("										</label>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("									<button type=\"submit\" class=\"button purple-btn full-btn submit-btn-style\">로그인</button>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"login-bottom-btn-box\">\r\n");
      out.write("									<p class=\"sign-up\">\r\n");
      out.write("										<a href=\"/account/user/register.do\">회원가입</a>\r\n");
      out.write("									</p>\r\n");
      out.write("									<div class=\"find-info-btn\">\r\n");
      out.write("										<a href=\"/account/user/find-id.do\" class=\"forgot-id\">아이디 찾기</a>\r\n");
      out.write("										<span> | </span>\r\n");
      out.write("										<a href=\"/account/user/find-pw.do\" class=\"forgot-pw\">비밀번호 찾기</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								\r\n");
      out.write("								</div>\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- content-wrapper ends -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- row ends -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- page-body-wrapper ends -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- container-scroller -->\r\n");
      out.write("	<!-- plugins:js -->\r\n");
      out.write("	<script src=\"/account/asset/js/vendor.bundle.base.js\"></script>\r\n");
      out.write("	<!-- endinject -->\r\n");
      out.write("	<!-- Plugin js for this page -->\r\n");
      out.write("	<!-- End plugin js for this page -->\r\n");
      out.write("	<!-- inject:js -->\r\n");
      out.write("	<script src=\"/account/asset/js/off-canvas.js\"></script>\r\n");
      out.write("	<script src=\"/account/asset/js/hoverable-collapse.js\"></script>\r\n");
      out.write("	<script src=\"/account/asset/js/misc.js\"></script>\r\n");
      out.write("	<script src=\"/account/asset/js/settings.js\"></script>\r\n");
      out.write("	<script src=\"/account/asset/js/todolist.js\"></script>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<!-- endinject -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/inc/header.jsp(109,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	           	 	<a href=\"/account/user/login.do\" class=\"header-content \">로그인</a>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/inc/header.jsp(112,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	           	 	<a href=\"/account/user/logout.do\" class=\"header-content \">로그아웃</a>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
